### ISSUE TITLE
AC <> TSC meeting during ACS

### ISSUE THREAD

**Issue by tobie** [ampproject/meta-tsc#19]
It would be great to organize a meeting (and maybe also a social event?) between the AC and TSC during the contributor summit.

We can discuss this here and/or discuss it during the [next TSC meeting](https://github.com/ampproject/meta-tsc/issues/18).

## ToDos:

- [ ] Find adequate time (for info the AC will be meeting the whole day on the 8th, that could be the occasion, else during the unconf parts of ACS).
- [ ] Decide on whether or not to hold a social event, and if so, when and where.
- [ ] Hash out agenda.

**Comment by rudygalfi** [comment]
Sounds great!

**Comment by dvoytenko** [comment]
My notes:
* Consider AC meet on the first day
* Confirm next TSC meet who can make the summit

**Comment by tobie** [comment]
Gentle ping to schedule a slot on Tuesday: https://github.com/ampproject/meta-ac/issues/47. /cc @rudygalfi
